"""Date fored added

Revision ID: 52f51e4ca464
Revises: 1a7360314c0f
Create Date: 2024-12-24 11:24:24.329945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52f51e4ca464'
down_revision: Union[str, None] = '1a7360314c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('date_formed', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'date_formed')
    # ### end Alembic commands ###
